{"name": "test_registration_00001", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <False>, but was not.", "trace": "self = <test_login.TestCart testMethod=test_registration_00001>, number = '07448061886'\n\n    @allure.testcase(\"Login Test\")\n    @allure.description(\"Testing the login functionality for ThreeUK\")\n    @file_data(\"C://Users//atique.shaikh//OneDrive - Accenture//Desktop//Python - \"\n               \"Framework//Selenium//git-selenium-framework2//datafiles//login.json\")\n    @pytest.mark.run(order=1)\n    def test_registration(self, number):\n>       self.login.perform_login(number)\n\ntests\\test_individual\\test_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.page_login.login_page.Login object at 0x0000017E315E8C70>, number = '07448061886'\n\n    @allure.step(\"Performing login action\")\n    def perform_login(self, number):\n        self.elementClick(self.lp.register)\n        self.elementSend(self.lp.number, number)\n>       assert_that(self.isElementPresent(self.lp.error_message)).is_false()\nE       AssertionError: Expected <False>, but was not.\n\npages\\page_login\\login_page.py:23: AssertionError"}, "description": "Testing the login functionality for ThreeUK", "steps": [{"name": "Performing login action", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <False>, but was not.\n", "trace": "  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\atique.shaikh\\OneDrive - Accenture\\Desktop\\Python - Framework\\Selenium\\git-selenium-framework2\\pages\\page_login\\login_page.py\", line 23, in perform_login\n    assert_that(self.isElementPresent(self.lp.error_message)).is_false()\n  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\assertpy\\base.py\", line 279, in is_false\n    self.error('Expected <False>, but was not.')\n  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "parameters": [{"name": "number", "value": "'07448061886'"}], "start": 1626641956190, "stop": 1626641957688}], "attachments": [{"name": "log", "source": "63bc5cf1-c4d5-4862-b6b8-cbd2c237da40-attachment.txt", "type": "text/plain"}], "start": 1626641956190, "stop": 1626641957711, "uuid": "fb182dd3-4101-438f-8510-5be5671a98b1", "historyId": "8993f510cf39a3ef384a0cd708c9f7d2", "testCaseId": "c6dd9e7e67532b74842795710cea522b", "fullName": "tests.test_individual.test_login.TestCart#test_registration_00001", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetup')"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "tests.test_individual"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestCart"}, {"name": "host", "value": "CPX-5HW8LFP40FY"}, {"name": "thread", "value": "15336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_individual.test_login"}], "links": [{"type": "test_case", "url": "Login Test", "name": "Login Test"}]}